name: 'Setup Protoc'
description: 'Setup protoc for action run'
inputs:
  version:
    description: 'version of protoc to setup'
    required: true
  token:
    description: 'github access token'
    required: true
  prereleases:
    description: 'should prerelease versions be included in search'
    required: false
    default: 'false'
runs:
  using: 'node16'
  main: 'dist/index.js'
